### ISSUE TITLE
TODO Climbing robots

### ISSUE THREAD

**Issue by mfocchi** [mfocchi/todo#1]
- [x] (Luigi) check if we can introduce spring force as a conservative force and if we need to compensate for non linear terms
- [x] (Luigi) implement properly dirac impulse mapping to state change 
- [x] (Mohammad) Simulate state machine for multiple jumps
- [x] (Mohammad) Write equations for kinetic energy in the document with its simplifications
- [x] (Mohammad/Michele) Optimizer with the spring
- [x] (Andrea) setup urdf for full model with leg
- [x] (Daniele) analyze controllability with lie brackets
- [ ] (somebody) design the leg prismatic joint with an electromagnet and a spring
- [x] (Michele) parametric sin(theta) with polynomials to make the problem less non linear
- [x] (Michele) use energy instead of derivative of energy to avoid double derivatives
- [ ] (Michele) impement RRT for obstacle avoidance
- [x]  (Michele) impement DP for multiple jumps
-  [x]  (Marco) impement optimal control  for 1 jump
-   [x]  (Michele) implement ICP for landing
- [x] (Michele) Implemented Gazebo simulator for 3D model

**Comment by mfocchi** [comment]
PAPER:

- [x] collect state of the art
- [x] comparison optimal control, polynomial optimization
- [x] Gazebo simulation with jumps
- [x] implement c++ version of optimization with polynomials
- [x] try if the optimized jump parameters work with Matlab sim and with gazebo Sim

**Comment by mfocchi** [comment]
JOURNAL
- [x] friction cones have no generic orientation
- [] contact location optimization
- [x] implemented fixed slack on final
- [x] how did we solve integration issues
- [ ] Gaussian normalization
- [ ] with the reset impulse approach  we have a smaller number of states
- [x] no constraint on p0
- [ ] dt depends on TF, time optimization
- [ ] optical fiber for harsh environment 
- [x] adding propellers to enhance landing and correct orientation error (cannot use flywheel due to presence of rope)
- [x] energy consumption comparison table wrt drone and other wheeled solutions of the same scale (gecko does not scale)

**Comment by mfocchi** [comment]
- [x] (michele) slider model
- [x] (michele) slider simulation Gazebo
- [x] (michele) slider simulation matlab 
- [x] (michele) 2 ropes model (redundant)
- [x] (Michele) move stuff from notes to journal paper
- [ ] (Marco ) integrate 2D mesh of rock face with derivative
- [x] (luigi) 2 ropes model (minimal)
- [x] (michele) 2 ropes model Gazebo
- [x] (michele) 2 ropes model Matlab
- [x] (michele) 2 ropes model static analysis
- [x] (marco) optimization with 2 ropes model
- [x] (marco) optimization with slider
- [x] (michele) ICRA corrections 
- [x] (Marco) slides per video 
- [x] (michele) updload video youtube on HYDRA
- [x]  Can authors add a map or comparison list between other
climbing robots for the cost of climbing? And we can see a
detailed place of their robot in terms of energy efficiency
between climbing robots out in the literature?
- [x] (Marco) adding patch to avoid obstacles

**Comment by mfocchi** [comment]
LANDER CONTROL
- [x] (michele) Impelent 2 additional wheel joints
- [x] (michele) Impelent kinematic adjustments to align the feet or low compliance at landing
- [x] (michele) Emulate cartesian spring damper at landing and test with slanted wall where I makes the difference
- [x] (michele) implement orientation control

**Comment by mfocchi** [comment]
WRITING
- [x] static analysis

**Comment by mfocchi** [comment]
- [ ] approx 2 ordine del seno for slider model
- [x] implement orientation control with disturbance
- [x] compute simplidied model 
- [x] Matlab optim  2 ropes  modello compact
- [x] confronto model esplicito

**Comment by mfocchi** [comment]
Journal 
1) implement angular dynamics 
2) do exps with sloped terrain and changing contact normal at liftoff and landing 
2) aggiunta propellers (la forza lineare si annulla per cui non disturba la traiettoria del com)

4) aggiunta contact point intermedio

**Comment by mfocchi** [comment]
check if landing error in gazebo is due to the discretization of impulse that lasts only 1 sample
Future works:

- [x] wrench polytope
- [x] use propellers to correct underactuated part
- [ ] use propellers to correct angular part
- [ ] MPC with time optimization

**Comment by mfocchi** [comment]
PAPER TRO WRITING

- [x] MPC can correct only on Y,Z
- [x] nT Fleg
- [x] singularity for px = 0 
- [x] video (leg reorient)
- [x] validation plot
- [x] clean code

video todo: 
- [x] panoramica muro
- [x]  cerchietto in robot
- [x] close up robot in parallelo
- [x] (Michele) redo video with less arrows
- [x]  add noise to multiple jumps , disturbance constant and impulsive 
Polytopes:
- [x] (Michele) solve LP to get margin given We, v 
- [x] write polytope section 
- [x] implement function that computes the fwp in half space description given as inputs : com position, b_R_w base orient, Fr,r0, Fr,l0, massa 
- [x] (Michele) redo video with less arrows
- [x]  add noise to multiple jumps , disturbance constant and impulsive 

REBUTTAL RAS:
- [x] evaluate drilling forces 

TODO codice
- [ ] add regularization of tangential velocity to optimization 

 
Presentazione
- [ ] show polytope
- [ ] specify leg dofs
- [ ] MPC constraints
- [ ] slack on landing position
- [ ] reoptimize MPC



CODE
- [x] simplify code for prototype
- [ ] chanth Tth as optim variable

**Comment by mfocchi** [comment]
MPC Horizon: 0.6 N no disturbance (BAD)
![image](https://github.com/mfocchi/todo/assets/3658459/072d5466-e5dd-43d5-88d8-5f1fc807fa9b)


MPC horizon: 0.4N no disturbance
![image](https://github.com/mfocchi/todo/assets/3658459/46c77ec7-effc-457d-9a18-1cca04677609)

MPC Horizon: 0.4 N No consrtaints    impulsive disturbance
target achieved (in matlab convention) is: [ 0.04771  4.08192 -4.02765]  while it should be  [ 0.29328  4.14287 -3.88566]
 the error is  0.29013369967999364

![image](https://github.com/mfocchi/todo/assets/3658459/090ccc08-5718-4ab7-bcca-3c4170f2a3ec)


MPC Horizon: 0.4 N With constraints  impulsive disturbance
target achieved (in matlab convention) is: [ 0.06867  3.88118 -4.14265]  while it should be  [ 0.28985  3.98675 -3.98834]
the error is  0.2896182561576231
![image](https://github.com/mfocchi/todo/assets/3658459/a05f6ad1-ea32-4f99-8d3f-467ad12d478e)

No MPC   impulsive disturbance
target achieved (in matlab convention) is: [-0.0008   3.07909 -3.25919]
 while it should be  [ 0.25456  3.98937 -4.05105]
 the error is  1.2332382267967064
![image](https://github.com/mfocchi/todo/assets/3658459/dee5b76c-b32e-46e2-b569-e71506abe493)

No MPC  no disturbance
target achieved (in matlab convention) is: [ 0.01323  3.81698 -4.20551]  while it should be  [ 0.16887  3.99539 -4.03691]
 the error is  0.29065957197473596
![image](https://github.com/mfocchi/todo/assets/3658459/b6104d9e-e3d0-4a38-b2e4-cf7a61867421)


MPC Horizon: 0.4 N With constraints no disturbance
target achieved (in matlab convention) is: [ 0.03147  3.93925 -4.1351 ]  while it should be  [ 0.25899  4.0007  -3.9881 ]
 the error is  0.2777603945854348
![image](https://github.com/mfocchi/todo/assets/3658459/17755fc2-f0f0-4764-9ad1-597879fc36a7)

**Comment by mfocchi** [comment]
MPC constant dist Y = -7 N
target achieved (in matlab convention) is: [ 0.03139  3.6363  -4.1224 ]  while it should be  [ 0.26518  4.06322 -3.97842]
 the error is  0.5075875847062675
![image](https://github.com/mfocchi/todo/assets/3658459/0368fb5e-91a5-4691-a0b9-4abad9f03001)

NOMPC constant dist Y = -7 N
target achieved (in matlab convention) is: [ 0.07417  2.74906 -4.25675]  while it should be  [ 0.30225  4.15032 -3.88873]
 the error is  1.4666290984408317
![image](https://github.com/mfocchi/todo/assets/3658459/84c5860c-133d-4a50-8469-e4ac0c56d154)

**Comment by mfocchi** [comment]
With constant dist I need to run MPC till the end of the horizon
![image](https://github.com/mfocchi/todo/assets/3658459/7f3c389e-dab9-4a35-b340-9658e45e60e4)

otherwise is like this 
![image](https://github.com/mfocchi/todo/assets/3658459/d8ba0066-6624-4ff1-833a-50f04847e112)

**Comment by mfocchi** [comment]
video todo: 
1) panoramica muro
2) cerchietto in robot
2) close up robot in parallelo

**Comment by mfocchi** [comment]
Self stabilyzing effect on Roll X

![image](https://github.com/mfocchi/todo/assets/3658459/a1e5962c-c883-45cc-8edd-f3f7a0d42a14)

is not really returning to the 0 position but to different values depending on the disturbance and on the rope length, when landing 

these final bias values seem smaller when the rope are longer 
![image](https://github.com/mfocchi/todo/assets/3658459/ab399dda-5c38-486e-92d1-0ad92fb3dec8)

**Comment by mfocchi** [comment]
Multiple jump tests (only 0 and 7 are bad the other are ok)

![image](https://github.com/mfocchi/todo/assets/3658459/47bf7744-ba6b-4007-8786-85b218a998ed)

**Comment by mfocchi** [comment]
Polytopes

- [ ] (Michele) solve LP to get margin given We, v 
- [ ] write polytope section 
- [ ] implement function that computes the fwp in half space description given as inputs : com position, b_R_w base orient, Fr,r0, Fr,l0, massa
