### ISSUE TITLE
TODO hopper robot

### ISSUE THREAD

**Issue by mfocchi** [mfocchi/todo#2]
- [x] (Michele Andrea) jump optimization with crocoddyl for comparison
- [x] (Riccardo) RL with torques, give low reward with target distance even if TD is not achieved to encourage moving toward target
- [x] (Ricccardo) Eval extrapolation quality with Max Number of training episodes. Create Feasible region: generate random inference set of N points with the same seed, inside thetraining region, and use that to compute reward that is associated with a color code to each target, 
- [x] (Riccardo) Plot different feasible regionr (expect assymmetric) with different number of episodes
- [ ] (Michele Riccardo) Create pointcloud map from 3d rough terrain (eval targetZ (X,Y))
- [x] (Riccardo) Repeat training with torque limits 2
Future:
- [ ] Robustness: add uncertainty on link masses  during training phase (expect to get more conservative trajectories)
- [ ] Robustness: start jump to test terrain compliance, do learning with different terrain compliances
- [ ] Simulate multiple robots with coppelia sim that update the same target network

**Comment by mfocchi** [comment]
add gravity comp to controller part in paper
define that we have only 1 state

**Comment by mfocchi** [comment]
1) no issue of self collision as in butter paper https://arxiv.org/pdf/2109.11978.pdf
2) robust learning with representative parameter obtained with heuristic template motion.  uncertainties of the physical parameters, e.g., dynamics  randomization, can be viewed as external forces applied to the robot(Sim-to-real: Learning agile locomotion for quadruped robots)
3) computational time is spent on contact detection and handling. Reduc-ing the number of potential contact pairs increases simulation throughput.We optimize the modelof the robot to keep only the necessary collision bodies: feet, shanks, knees, and the base.
4) To bridge the reality
gap, a series of measures such as increasing the noise level,
adding latency and domain randomization are implemented.
We assume Gaussian distribution to be present on the real
robot for all quantities in the observation space.
5) learn also the controller parameters

**Comment by mfocchi** [comment]
- [x] try with smaller neurons (64) to see the training gets slower (find smallest network size) 
- [x] evaluate different simulators to run multirobot that mutually update same target policy . These are new API of openAI Gymhttps://github.com/Farama-Foundation/Gymnasium
- [x] extend to quadruped
- [x] add WBC to orbit
- [x] fix jacobian  github.com/NVIDIA-Omniverse/orbit/    issues/267
- [x] change step function to be updated when we want
- [x] ffwd kinematics
- [x] gravity compesnation lower gains
- [x] add tracking of position com_lo
- [x] do all tests with the final parameytric setup (layers/neurons/number of episodes /
 compare with / without feasibility check reward)
- [x] torques training (scaling) (does not work)
- [x] optimization
- [x] add plot of error for different layers / ideal landing cost (jump feasibility check)
- [x] put relative error %
- [x]  add translucid convex hull RPE 50 VS RPE 10 for 50k episodes
- [x] separate front graph back graph
- [x] do bigger test zone
- [x] redo video with few balls
- [x] do jump down from pallet
- [ ] add continuous jumping
- [ ]  swing optimization
- [ ] learn to jump while not static (e.g. running)
https://github.com/Improbable-AI/rapid-locomotion-rl : try Isaac gym
- [ ]  test with deformable trampuline
- [ ] do training for robustness in simulation and do domain improvement in experiments




Comparison:
1) learning different policies with / without rearing
2) different low levels PD / MPC
3) with without delta tau 
[ ] learn a single jump forward (only linear), do grid search on reward weights (target, tochdown)

- [x] per evitare che impari i saltini metto rewward con alto peso al TD e se non fa TD reward con basso peso alla fine dell'episodio per essere informativa
- [ ] aggiungere rete che impari il landing controller
- [x] test with pitch jumping on slope-> error
- [x] test with pure yaw->error

**Ablation**:
default scenario: positive reward at the initial TD and negative when end position at the end of episode is different from 1st TD
- [ ]  try 3 different coeff. d'attrito
- [x]  remove negative penalization from the bouncing after TD  / remove also joint torques limits
- [ ] test with different masses
- [ ]  implement controller with lift off of forward legs (rearing motion)

**Comment by mfocchi** [comment]
- [ ] add tracking of com_lo

**Comment by mfocchi** [comment]
New ideas
1) carlos Mastalli: learn timings for MPC, tossing robot
2) non zero velocity jump, learn when to jump on obstacle setting where to land

**Comment by mfocchi** [comment]
1) add translucid convex hull RPE 50 VS RPE 10 for 50k episodes
2) separate front graph back graph
3) do bigger test zone

**Comment by mfocchi** [comment]
New IIT exchange
1) extend to quadruped
2) swing optimization
3) learn to jump while not static (e.g. running)

**Comment by mfocchi** [comment]
https://github.com/NVlabs/CALM

add hutter paper

**Comment by mfocchi** [comment]
video 

readme code repo

**Comment by mfocchi** [comment]
do jump down from pallet

**Comment by mfocchi** [comment]
implement controller with lift off legs

**Comment by mfocchi** [comment]
add WBC to orbit
add landing controller to quadruped_jump_control
add training with landing aware reward

**Comment by mfocchi** [comment]
per evitare che impari i saltini metto rewward con alto peso al TD e se non fa TD reward con basso peso alla fine dell'episodio per essere informativa
in futuro aggiungere rete che impari il landing controller
test with pitch jumping on slope-> error
test with pure yaw->error

**Comment by mfocchi** [comment]
solve bug on contact forces

**Comment by mfocchi** [comment]
PAPER TODO

- [x] merging thesis writing (Michele, Riccardo) https://www.overleaf.com/project/672a2f819fe17b149ab97eab
- [ ] video editing go1 / aliengo (Giulio)
- [x] Locosim Simulations with added noise / non linearity for repeatibility (Michele)
- [ ] code push (Riccardo)
- [ ] Isaac sim plots  (Riccardo)

folder with the videos:  https://www.dropbox.com/scl/fo/u2i9eea3m6wl9pkqstbk1/AFvFgllVSN-wONyQFffV_s0?rlkey=8kyd65n7up5604mlb6po6hbtc&dl=0

bugfix:
- equalize the models, q0, startup conditions, retraction configs in ORBIT / locosim before code delivery
- fix calcolo accelerazione explosion considerando diverse altezze tra locosim e orbit
- overlay on video the graduated scale of the target
-
