### ISSUE TITLE
TODO delle vedove joel

### ISSUE THREAD

**Issue by mfocchi** [mfocchi/todo#3]
- [ ] spawn 2 robots in gazebo
- [ ] load 2 (joint_group_pos..) controllers for the 2 robots
- [ ] import the Zed2 camera on the tool0 frame of the 2 robots
- [ ] move both robots with sines in joint config to acquire data
- [ ] improve estimation of th object you want to see merging data coming from the 2 robots
- [ ] check paper of Andrea https://hal.science/hal-01574819/document

**Comment by matteodv99tn** [comment]
@mfocchi We are trying to spawning multiple robots, but we have some issues. Are you available on friday evening to discuss a bit?
Thank you in advance,
Matteo and Joel

**Comment by mfocchi** [comment]
Im out of Trento, on monday I am available

**Comment by matteodv99tn** [comment]
For us in the evening is fun, let us know the hour you prefer!

**Comment by mfocchi** [comment]
ok verso le 1430
